### ISSUE TITLE
Request to add multi-language support to the GUI

### ISSUE THREAD

**Issue by wcxu21** [DHancock/SudokuSolver#323]
Hi there dear developer.
I'm from China, thank you very much for developing this app, it's great.
I tried to download this app and I noticed that it only supports English. Is it possible for you to add multi-language support for this project so that more users with different languages can experience it better.
I can provide you with a Chinese translation and I'm sure more project enthusiasts will participate in the localisation.
You can provide online translation of the project (e.g. Weblate) or provide the character files to be translated, and I will translate them and apply for merge branch.
Thank you for your work.

**Comment by DHancock** [comment]
Ok, leave it with me and I'll let you know when it's ready.

**Comment by DHancock** [comment]
I've added a Chinese translation to the app using traditional script. The file is:

SudokuSolver/Resources/zh-Hant/Resources.resw

It was translated using Microsoft's azure translation service. I'm not sure how correct it is, machine translations don't really understand context. If you could take a look or build the app to see the new text.

A couple of questions:

- Is there a need to supply a Chinese trnslation using the simplified script? (zh-Hans)
- Is there a big benifit translating the installer as well?

**Comment by wcxu21** [comment]
To translate Chinese, I recommend you use Google Translate or the German Deepl online translation. The translation content they provide will be of better quality.
I will use them as a reference for most of the content and make changes based on the actual situation.
I re-translated it into Simplified Chinese language, and since I'm not familiar with Traditional Chinese, I didn't help with the revisions.
Thank you for your work.

**Comment by DHancock** [comment]
Thank you for providing the update. 
Fixed by change [#332](https://github.com/DHancock/SudokuSolver/pull/332)
