### ISSUE TITLE
The visual studio does not show the XAML UI designer 

### ISSUE THREAD

**Issue by chucklu** [DHancock/SudokuSolver#414]
I  have checked this, https://stackoverflow.com/questions/30090719/xaml-designer-not-showing-up
and I am sure the XAML designer is enabled

Tools>Option>XAML Designer 

do I need do something else to make the xaml designer show?

**Comment by DHancock** [comment]
This code uses the Windows App Sdk and Microsoft don't currently provide an xaml designer for it. Personally I've never used designers, I learn to and prefer just to write xaml directly. Although a lot of people have raised this issue with Microsoft. The relevent issue (in the correct repository) is:

https://github.com/microsoft/microsoft-ui-xaml/issues/5917
