### ISSUE TITLE
Does this app support solve the sudoku step by step like sudokuwiki does?

### ISSUE THREAD

**Issue by chucklu** [DHancock/SudokuSolver#417]
solve the sudoku step by step like this, and list the strategy used to each step
https://www.sudokuwiki.org/Sudoku.htm
139005608720090010400001090001600900003008001070002030084000179002007000007009254

Naked Triple
Naked Triple 3/6/8 in Row H, on cells [H7,H8,H9]
- removes 3/6 from H1
- removes 6 from H2
- removes 3/8 from H4
- removes 3/6/8 from H5
Naked Triple 3/5/6 in Col 9, on cells [B9,F9,H9]
- removes 3/5 from C9
- removes 5 from D9

Pointing Pairs
PAIR: Between Box 3 and Row 3:
7 taken off C4
7 taken off C5

Pointing Pairs
PAIR: Between Box 1 and Col 3:
8 taken off F3

Naked Pair
Naked Pair 5/6 in Row F, on cells [F3,F9]
- removes 5/6 from F1
- removes 5 from F4
- removes 5 from F5
- removes 5 from F7

Rectangle Elimination
If +4[D8] then -4[D6] forcing +4[B6] which removes all 4s from box 3, so D8 cannot be 4

Y-Wing
Y-Wing pattern. Hinge: D8 (2/8), wings A8 F7, therefore
4 can be taken off B7
4 can be taken off E8

SINGLE: A8 set to 4, unique in Column and Box

SINGLE: C9 set to 2, unique in Box

SINGLE: D9 set to 7, unique 

SINGLE: C7 set to 7, unique in Row and Column and Box

Naked Pair
Naked Pair 3/5 in Row B, on cells [B7,B9]
- removes 5 from B3
- removes 3 from B4
- removes 3 from B6

Naked Triple
Naked Triple 3/4/5 in Row D, on cells [D2,D5,D6]
- removes 5 from D1

XY-Chain
length=4, chain ends: C4 and G6
This proves 3 is the solution at one end of the chain or the other
-3[C4]+8[C4]-8[B4]+4[B4]-4[B6]+6[B6]-6[G6]+3[G6]
3 taken off G4
3 taken off J4

**Comment by DHancock** [comment]
The simple answer is no it doesn't. 

SudokuWiki is for enthusiasts who like to analysis puzzles in great detail. Your average amateur player won't want to go into that much detail. That includes me. Providing all that extra details considerably complicates the ui which in the majority of cases will be detrimental to the playing experience. I wanted a program that was simple to use. If you need the detail that SudokuWiki provides just use that (or any of the simmiler others).
